// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 10.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SourcePro.Csharp.Lab.Generators
{
    using System;
    
    
    #line 1 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class TemplateGenerator : TemplateGeneratorBase
    {
        public virtual string TransformText()
        {
            this.Write("@@ Assembly Info Manager Template\r\n@@ Create Time : ");
            
            #line 3 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")));
            
            #line default
            #line hidden
            this.Write("\r\n@@ Machine Name : ");
            
            #line 4 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Environment.MachineName));
            
            #line default
            #line hidden
            this.Write("\r\n@@ Current User : ");
            
            #line 5 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Format("{0}\\{1}", Environment.UserDomainName, Environment.UserName)));
            
            #line default
            #line hidden
            this.Write("\r\n@@ Installed Directory : ");
            
            #line 6 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AppDomain.CurrentDomain.BaseDirectory));
            
            #line default
            #line hidden
            this.Write("\r\n@@ Project Url : https://github.com/SourceproStudio/Utility/tree/AssemblyInfoMa" +
                    "nager\r\n@@ Developer : Wang Yucai\r\n@@ E-mail : MasterDuner@Yeah.net or Yucai.Wang" +
                    "-Public@Outlook.com\r\n@@ Copyright © ");
            
            #line 10 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.Now.Year));
            
            #line default
            #line hidden
            this.Write(" Wang Yucai. All rights reserved.\r\n\r\nusing System.Reflection;\r\nusing System.Runti" +
                    "me.InteropServices;\r\n\r\n@@ Assembly Base Information\r\n[assembly: AssemblyTitle(\"");
            
            #line 16 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TemplateObject.Title));
            
            #line default
            #line hidden
            this.Write("\")]\r\n[assembly: AssemblyDescription(\"");
            
            #line 17 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TemplateObject.Description));
            
            #line default
            #line hidden
            this.Write("\")]\r\n[assembly: AssemblyCompany(\"");
            
            #line 18 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TemplateObject.CompanyName));
            
            #line default
            #line hidden
            this.Write("\")]\r\n[assembly: AssemblyProduct(\"");
            
            #line 19 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TemplateObject.ProductName));
            
            #line default
            #line hidden
            this.Write("\")]\r\n[assembly: AssemblyCopyright(\"");
            
            #line 20 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TemplateObject.Copyright));
            
            #line default
            #line hidden
            this.Write("\")]\r\n[assembly: AssemblyTrademark(\"");
            
            #line 21 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TemplateObject.Trademark));
            
            #line default
            #line hidden
            this.Write("\")]\r\n\r\n@@ Assembly Version\r\n");
            
            #line 24 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
 
    if(this.TemplateObject.Version.AutoGenerateRevisionNumber && !this.TemplateObject.Version.AutoGenerateBuildNumber)
    {

            
            #line default
            #line hidden
            this.Write("[assembly: AssemblyVersion(\"");
            
            #line 28 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TemplateObject.Version.Major));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 28 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TemplateObject.Version.Minor));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 28 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TemplateObject.Version.Build));
            
            #line default
            #line hidden
            this.Write(".*\")]\r\n");
            
            #line 29 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
 
    }
    if(this.TemplateObject.Version.AutoGenerateRevisionNumber && this.TemplateObject.Version.AutoGenerateBuildNumber)
    {

            
            #line default
            #line hidden
            this.Write("[assembly: AssemblyVersion(\"");
            
            #line 34 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TemplateObject.Version.Major));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 34 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TemplateObject.Version.Minor));
            
            #line default
            #line hidden
            this.Write(".*\")]\r\n");
            
            #line 35 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"

    }
    if(!this.TemplateObject.Version.AutoGenerateRevisionNumber && !this.TemplateObject.Version.AutoGenerateBuildNumber)
    {
        string version = this.TemplateObject.Version.ToString();

            
            #line default
            #line hidden
            this.Write("[assembly: AssemblyVersion(\"");
            
            #line 41 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(version));
            
            #line default
            #line hidden
            this.Write("\")]\r\n[assembly: AssemblyFileVersion(\"");
            
            #line 42 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(version));
            
            #line default
            #line hidden
            this.Write("\")]\r\n");
            
            #line 43 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
 
    }

            
            #line default
            #line hidden
            this.Write("\r\n@@ Generate by AssemblyInfoManager v");
            
            #line 47 "E:\CSharp\Mine\Utility\AssemblyInfoManager\Generators\TemplateGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetType().Assembly.GetName().Version.ToString()));
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class TemplateGeneratorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
